config/routes.rb
Whoa::Application.routes.draw do

  resources :questions do
    member do
      post :vote_up
    end

    member do
      post 'mark_answered'
    end
  end
 
  root 'welcome#index'

  #resources :questions
  
  resources :users, only: [:index, :new, :create]

  resource :session

  resource :welcome, only: [:index]

  resources :votes

  

  namespace :json do

    resources :questions do
      member do
        post :vote_up
      end

      member do
        post 'answered'
      end

      member do
        get :getvotes
      end

      member do
        get :getanswerable
      end

    end

  end






end

app/models/question.rb
class Question < ActiveRecord::Base

  # using thumbs_up gem
  acts_as_voteable

  # prevents entering null questions
  validates :details, presence: true

  # sets up AR relations
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :email, presence: true, uniqueness: true
	validates :name, presence: true

	has_secure_password

  acts_as_voter

	has_many :questions
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :proclamation
  belongs_to :user
  
  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, lambda { order("created_at DESC") }

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable if ActiveRecord::VERSION::MAJOR < 4


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/json/questions_controller.rb
class Json::QuestionsController < ApplicationController

# namespaced json controller to handle all the ajax requests from the page 

  #build the room from all of the current unanswered rooms - from a page refresh.
  def index
    #@questions = Question.order("created_at ASC").all
    @unanswered_questions = Question.where("answered = false").plusminus_tally
    #@user_id = session[:user_id]
    render json: [{questions: @unanswered_questions}] and return
  end

  #GET json/question/:id/getvotes
  #find out all the votes a certain question has
  def getvotes
    @the_question = Question.find(params[:id])
    render json: [{question: @the_question}, {votes: @the_question.votes_for}] and return
  end

  #POST json/question/:id/vote_up
  #vote for the question using thumbs_up method.
  #TODO: should return something else if error.
  def vote_up
    current_user = User.find(session[:user_id])
    @the_question = Question.find(params[:id])

    current_user.vote_for(@the_question)
  
    render json: [{question: @the_question}, {votes: @the_question.votes_for}]
  end

  #GET json/question/:id/getanswerable
  #find out if the user who is logged in can answer this particular question.
  #TODO: add in verification for Teacher Role
  def getanswerable
    @the_question = Question.find(params[:id])
    @user_id = session[:user_id]
    if @the_question.user.id == @user_id
      render json: [{question: @the_question}]
    end
  end

  #POST json/question/:id/answered
  #make the question answered, save it, return it as json obj.
  def answered
    @the_question = Question.find(params[:id])
    @the_question.answered = true
    @the_question.save
    render json: [{question: @the_question}]
  end


  #create a new question, save it, return it as a json obj.
  def create
    @question = Question.new(question_params)

    if @question.save
      render json: @question
    else
      render status: 400, nothing: true
    end
  end

  private

  def question_params
    params.require(:question).permit(:details, :user_id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_user, only: [:index, :mark_answered]
  before_action :authenticated!, only: [:index]

  def index
    @questions = Question.order("created_at ASC").all
    @unanswered_questions = Question.where("answered = false").plusminus_tally
    @user_id = session[:user_id]
    # binding.pry
  end
 
  def create
    @question = Question.new(question_params)
  
    if @question.save
      render json: @question
    else
      render status: 400, nothing: true
    end
  end
 
  def new
    render :new
  end
 
  def update
    @question = Question.find(params[:id])

    if @question.update
      render status: 200, nothing: true
    else
      render status: 400, nothing: true
    end
  end
 
  def destroy
    @question = Question.find(params[:id])
 
    if @question.destroy
      render json: {}
    else
      render status: 400, nothing: true
    end
  end
 
  def vote_up
    begin
      #binding.pry
      current_user = User.find(session[:user_id])
      
      @the_question = Question.find(params[:id])
      
      if current_user.vote_for(@the_question)
        render json: [{question: @the_question}, {votes: @the_question.votes_for}]
      else
        render status: 400, nothing: true
      end
      # @questions = Question.order("created_at ASC").all
      # render :index

    rescue ActiveRecord::RecordInvalid
      render json: @the_question.votes_for
    end
  end

  def mark_answered
    @question = Question.find(params[:id])
    # binding.pry
    @question.answered = true
    @question.save

    redirect_to questions_path

  end

  private 
 
  def question_params
    params.require(:question).permit(:details, :user_id)
  end
  # { :id => 1, :question => { :questions => "why?", :answered => false } }
  def authorized!
    if session[:user_id] == nil
      redirect_to new_session_path
    end
  end

  def set_user
    @current_user = User.find(session[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    # authenticate that user/pass combo is legit
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to questions_path#users_path #user_path(user)
    else
      redirect_to new_user_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def index
    @teachers = User.all #?????
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticated!, except: [:new, :create]

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
    	redirect_to users_path 
  	else
    	render :new
  	end
  end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def authorized!
  	unless @user.id == session[:user_id]
  		redirect_to user_path(session[:user_id])
  	end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
    	@home = true
    	if session[:user_id] == nil
    		render :index
    	else
    		redirect_to new_user_path
    	end
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    session[:user_id].present?
  end

  def authenticated!
    unless logged_in?
      redirect_to new_user_path
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnyQuestions</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <ul>
	<% if logged_in? %>
		<li><%= link_to 'Logout', session_path, :method => :delete %></li>
	<% else %>
		<li><%= link_to 'Login', new_user_path() + "/?a=login" %></li>
	<% end %> 
</ul>  
</nav>
<%= yield %>
</body>

<footer>

<% if logged_in? #user is logged in %>
        <br>
        <br>
        <%= "#{current_user.name} is currently logged in." %><br>
        <% if current_user.name != current_user.teacher %>
          <%= "#{current_user.name} is not a teacher." %>
        <% end %>
        

<% else %>
        <br>
        <br>
        <%= "No user is currently logged in." %>

<% end %>

</footer>
</html>

app/views/questions/error.html.erb
<h1> You have already upvoted this question. </h1>

app/views/questions/index.html.erb
<!-- making the javascript specific to this controller to avoid scope problems  -->
<%= javascript_include_tag params[:controller] %>
<%= javascript_include_tag "questions_model" %>
<!-- <script type="text/javascript" src="questions_model.js"></script> -->

<h1 class="questions">AnyQuestions <span class="dot">+</span></h1>

<!-- main div to allow everything to collapse, connected to toggle function in questions.js -->
<div class="container">
  
  <!-- form for inputting question -->
  <form name="question" method="get" class="question-form">
    <input type="text" placeholder="Type your question here" name="command" class="question">
    <button>Submit</button>
  </form>
  
  <!-- hidden field to hold user id for ajax requests -->
  <div id="session_id" style="visibility: hidden">
    <%= @user_id %>
  </div>

  <div class="packery">
  <!-- 
  <% @unanswered_questions.each do |question| %>
      <div class="item">
        <div class="item-content" data-val="<%= question.id%>">
        <%= question.details %>" posted by User        
        <div class="upButton">&oplus;</div>
        <div class=votesDiv><%= question.votes_for %></div>
       <% if (@current_user.teacher == true) || (question.user_id == session[:user_id]) %>
			   <%= button_to 'Answered', mark_answered_question_path(question[:id]), method: 'post' %>
    	  <% end %>

        </div>
      </div>
    <% end %> 
  -->
  </div> 

</div>
<!-- close container div -->

app/views/users/_form.html.erb
<!-- begin signup form -->
<% unless @user.errors.none? %>
  <% @user.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

<div id="form_wrapper" class="form_wrapper">
<%= form_for @user, html: {class: "register", id: "register"} do |f| %>
  <h3>Register</h3>
  <div class="column">
    <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
    </div>
    <div>
  <%= f.label :email %>
  <%= f.email_field :email %>
    </div>
  </div>
  <div class="column">
    <div>
  <%= f.label :password %>
  <%= f.password_field :password %>
    </div>
    <div>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
    </div>
  <div>
  <div class="bottom">
  <%= f.submit %>
  <% end %>
  <%= link_to "You have an account already? Log in here", new_session_path, class: 'linkform', rel: 'login' %>
    <div class="clear"></div>
    </div>
  </div>
</div>
<!-- end signup form -->

<!-- begin login form -->
<%= form_tag session_path, :method => :post, id: 'login',
 class: "login active" do %>
  <h3>Login</h3>
  <div>
  <%= label_tag :email %>
  <%= text_field_tag :email %>
  </div>
  <div class="bottom">
  <div>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  </div>
  <%= submit_tag "Login" %>
  <%= link_to "You don't have an account yet? Register here", new_user_path, class: 'linkform' , rel: 'register'%>
  <div class= "clear"></div>
  </div>
<% end %>
<!-- end login form -->

<script type="text/javascript">$(function(){
  console.log('<%= params[:a] %>');
  if ('<%= params[:a] %>' !== 'login') {
    $(".linkform").trigger("click");
  }
});</script>

app/views/users/index.html.erb
<div>
  <div>
    <h1>This is Woah<span>.</span></h1> 
  </div>
</div>

<div>
  <h3>
    Who's online?
  </h3>
</div>
<% @users.each do |u| %>
	<li><%= u.name %></li>
  <li><%= link_to "Questions", questions_path %></li>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h2> hello <%= @user.name %></h2>
<h2><%= @user.email %></h2>

app/views/welcome/index.html.erb
<div class="container">
	<h1 class="border">AnyQuestions<span class="container"><span class="dot">+</span> Better questions, better answers.</h1>

	<h3>AnyQuestions is a simple real-time classroom Q &amp; A tool that enables students to post and vote for questions.<br>Teachers can then identify questions to address on-the-spot, taking into account their popularity.
	</h3>
</div>


<!-- <div class="main">
	<a href="#wheel" class="wheel-button">
		<span>+</span>
	</a>
	<div class="pointer">Hover me</div>
		<ul id="wheel" class="wheel" data-angle="all">
			<li class="item"><%= link_to 'Home', root_path %></li>
			<li class="item"><%= link_to 'Login', new_user_path() + "/?a=login" %></li>
			<li class="item"><%= link_to 'Sign Up', new_user_path() + "/?a=signup" %></li>
			<li class="item"><a href="https://twitter.com/theangrydom" target= "blank">Questions</a></li>
			<li class="item"><%= link_to 'Sign Out', session_path, :method => :delete %></a></li>
			<li class="item"><a href="https://twitter.com/theangrydom" target="blank">Documentation</a></li>
		</ul>
	</div>
</div>  -->


		
<h1 class="border"></h1>
<!-- <footer>
<p class="back">By Team inJEANius [Justin,  Erica, Aby, Nichol] of the WDI September Array class.</p>
</footer> -->